### ISSUE TITLE
[Bug] Feature flags only update with a restart

### ISSUE THREAD

**Issue by august-growthbook** [growthbook/growthbook-golang#16]
### Summary

From the user:

> Feature flags don't update on GraphiQL. A restart is required for the changes to reflect.
Is it because of caching? What could be the potential solution here? 

#### Expected Behavior

Feature flags should update without a restart.

#### Current Behavior

Feature flags update only with a restart.

#### More info
https://growthbookusers.slack.com/archives/C01T6PKD9C3/p1694505434135549

**Comment by ian-ross** [comment]
There was a bug in the SSE library I use for getting streaming updates from GrowthBook (this issue: https://github.com/r3labs/sse/issues/147). This meant that an SSE connection dropped by the GrowthBook server was not reconnected properly. SSE client connections should deal with reconnection transparently, so this was a bug. There's no way for a server to know when the client at the other end of an SSE connection is still there, apart from waiting for the relevant TCP timeouts, so it's pretty normal to drop the connection on the server side periodically and to expect the client to reconnect. The GrowthBook server does this, but the bug in the SSE package I'm using prevented clean reconnection, so SSE updates appeared to stop coming.

I've now forked the dependency and fixed the problem (using an existing PR that's open on that package). Streaming updates now appear to be delivered indefinitely, and the connection to the server is re-established immediately each time that it's dropped.

This fix is in v0.1.6 of the SDK.

**Comment by ian-ross** [comment]
Closing as fixed in v0.1.6.

**Comment by august-growthbook** [comment]
Thank you so much, Ian! I'll let the customer who reported this know. We really appreciate how quickly you were able to resolve this!

**Comment by darkLord19** [comment]
@ian-ross @august-growthbook thanks a lot for quick fix. I will integrate latest version in our code and test.
